### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by prog20901** [JHierrot/openprodoc#1]

**Comment by JHierrot** [comment]
Thank you jkathir by you  interest.
Regarding your recommendations:
-  _Google like search engine like https://ambar.cloud/_    OpenProdoc Includes Lucene as Search Engine
-  _Next, Previous, Go to Option like Folio Views_     Can you explain better? In the folder or results  views you have a orderable table of documents.
-  _Number of hits found before hitting the actual search like Folio Views_  I'll review the functionality. I agree you can be useful.
-  _Import options from Zim, Treepad or other wikis._  You can import from file system a complete directory (in Swing version), however you would lost the integrity and style because each document is an independent element. The included importing, besides files, is from scanned images with metadata from Kofax Capture or Abby Flexicapture.
-  _Handling huge number of documents by providing quick search via Solr or Apache Lucene_ Included Lucene but not "quick search". I suppose you are thinking in suggestions like Google. Am I correct?
- _Support for tamil language_ Sadly I don't know tamil. However I will happy to include it (or any other language) if someone translate the language file (a 32K txt file )
- _Having tags for each document_ You can define your document types with any kind of metadata, including fields multivalued. (i.e. Keywords). In the examples included you can see document types with metadata as "Authors" or "Players"
-  _Built in web clipper (save webpages locally)_ I've in mind to include the possibility of edit documents with an included editor. But to copy and paste in the editor complete pages can be complex.
- _Support for full text search in huge text nodes_ OpenProdoc Includes Lucene as Search Engine so included.
-  _Quickest search results via indexing through Apache Lucene like docFetcher_ I don't understand. Why to search on results if you can search  mixing metadata and fulltext and iterate changing he conditions?

Regards

Joaquín Hierro

**Comment by prog20901** [comment]
1 - pls have a look for a minute https://ambar.cloud/ and http://table.branham.org/#/main  
the table shows the number of records found while typing and content is getting hightlighted
2 - pls see the folio views screenshots which has next, previous hit, navigation - ex: https://smhttp-ssl-50131.nexcesscdn.net/uploads/products_images/Screen_Shot_3.png  see the bottom of the image 
3 - pls watch this video for few mins and it explain the features..
4, 5, 7, 8, 9 and 10 - that's fine 
6 - For tamil fonts, please go through the following steps
Download http://www.azhagi.com/ software which is the tamil editor like
microsoft word
Type the text in different font like choosing in microsoft word
You can see the font as well as the text
Make sure the text is being supported
Fonts for your kind reference:
http://www.azhagi.com/freefonts.html#top1
http://tamil.indiatyping.com/index.php/download-tamil-font
http://www.freetamilfont.com/

please go through the folio views features and you will get an idea on how beautifully the searched content are found and rendered very quick and easy navigation.

docFetcher builts a quick search with highlighted text with next, previous options and renders the content for easy navigation with a side pane - example go through the page - http://www.williambranhamstorehouse.com/free/branham_sermon-search-wp.htm
