### ISSUE TITLE
Windows 10: the running program doesn't appear at taskbar

### ISSUE THREAD

**Issue by vilasha** [JHierrot/openprodoc#6]
Hi!
I downloaded portable version and trying to run it on my Win10 computer. And even though the program is launched, it didn't appear on taskbar, neither I can't switch to it with Alt+Tab
![prodoc_issue02](https://user-images.githubusercontent.com/31420205/41781420-5cb1f9cc-762f-11e8-9843-e25f383e1c79.jpg)

**Comment by JHierrot** [comment]
Hi,
This behaviour is just because the application didn't has "started", it's showing a modal form asking for user/password.
After you do the logging in the application, the complete application appears in the desktop and the taskbar.

![screenshot](https://user-images.githubusercontent.com/11455031/41789513-dd94dc06-764f-11e8-9244-76365375f52b.png)

Best Regards.
